my_project:
  outputs:
    dev:
      dbname: store
      host: 192.168.0.8
      pass: pass
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
